jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
